<?php
require_once __DIR__ . '/includes/site-data.php';
$slug = preg_replace('/[^a-z0-9-]/', '', strtolower($_GET['slug'] ?? ''));
$course = bdsi_find_course_by_slug($slug, $courseCatalog) ?? bdsi_find_additional_by_slug($slug, $additionalRoutes);
if (!$course) {
    http_response_code(404);
    $pageTitle = 'Course Not Found | Best Data Science Institute';
    $pageDescription = 'The requested course page could not be found.';
    require __DIR__ . '/includes/header.php';
    echo '<main><section class="bdsi-page-hero"><div class="container-xl"><div class="bdsi-eyebrow">404</div><h1>Course page not found</h1><p class="bdsi-copy">Explore our current training programs or contact us for guidance.</p><a class="bdsi-btn mt-3" href="/courses.php">View All Courses</a></div></section></main>';
    require __DIR__ . '/includes/footer.php';
    exit;
}
$pageTitle = $course['title'] . ' | Best Data Science Institute';
$pageDescription = $course['summary'] . ' Practical training in Jaipur with projects and career guidance.';
$canonical = $bdsi['url'] . $course['route'];
require __DIR__ . '/includes/header.php';
?>
<main>
<section class="bdsi-page-hero">
  <div class="container-xl">
    <div class="row g-5 align-items-center">
      <div class="col-lg-8"><div class="bdsi-kicker"><?= htmlspecialchars($course['category']) ?></div><h1 class="mt-3"><?= htmlspecialchars($course['title']) ?></h1><p class="bdsi-lead mt-3"><?= htmlspecialchars($course['summary']) ?></p><div class="d-flex flex-wrap gap-3 mt-4"><button class="bdsi-btn" data-bs-toggle="modal" data-bs-target="#enquiryModal">Book Free Demo</button><a class="bdsi-btn bdsi-btn-outline" href="tel:+919116036041">Call Admissions</a></div><div class="bdsi-proof"><?php foreach(array_slice($course['tools'],0,5) as $tool): ?><span><?= htmlspecialchars($tool) ?></span><?php endforeach; ?></div></div>
      <div class="col-lg-4"><div class="bdsi-card"><div class="bdsi-eyebrow">Program overview</div><h3 class="h4"><?= htmlspecialchars($course['short']) ?></h3><ul class="bdsi-list"><li><?= htmlspecialchars($course['duration']) ?></li><li>Guided practical exercises</li><li>Project-focused learning</li><li>Interview preparation support</li><li>Course counselling before enrollment</li></ul><button class="bdsi-btn w-100 mt-3" data-bs-toggle="modal" data-bs-target="#enquiryModal">Request Details</button></div></div>
    </div>
  </div>
</section>

<section class="bdsi-section">
  <div class="container-xl"><div class="row g-5"><div class="col-lg-8"><div class="bdsi-eyebrow">What you will learn</div><h2 class="bdsi-title">A practical learning roadmap</h2><p class="bdsi-copy mt-3">The curriculum moves from foundations to applied work so that each topic is practiced before it is used in larger projects.</p><div class="row g-3 mt-4"><?php foreach($course['modules'] as $i=>$module): ?><div class="col-md-6"><div class="bdsi-card"><div class="bdsi-chip">Module <?= $i+1 ?></div><h3 class="h5 mt-2 mb-0"><?= htmlspecialchars($module) ?></h3></div></div><?php endforeach; ?></div></div><aside class="col-lg-4"><div class="bdsi-course-side"><div class="bdsi-form-card"><div class="bdsi-eyebrow">Get course details</div><h3 class="h4">Talk to a counsellor</h3><form class="bdsi-lead-form" action="/submit-enquiry.php" method="post"><div class="mb-3"><label>Full name *</label><input class="form-control" name="full_name" required></div><div class="mb-3"><label>Mobile *</label><input class="form-control" name="phone" required inputmode="tel" pattern="[0-9+() -]{8,18}"></div><div class="mb-3"><label>Email</label><input class="form-control" type="email" name="email"></div><input type="hidden" name="course" value="<?= htmlspecialchars($course['short']) ?>"><input type="hidden" name="city" value="Jaipur"><input type="hidden" name="qualification" value=""><input type="hidden" name="preferred_mode" value=""><input type="hidden" name="source_url" value=""><input type="hidden" name="utm_source" value=""><input type="hidden" name="utm_medium" value=""><input type="hidden" name="utm_campaign" value=""><input type="hidden" name="utm_term" value=""><input type="hidden" name="utm_content" value=""><input type="text" name="website" style="position:absolute;left:-9999px" tabindex="-1" autocomplete="off"><button class="bdsi-btn w-100" type="submit">Request Call Back</button><div class="bdsi-toast" aria-live="polite"></div></form></div></div></aside></div></div>
</section>

<section class="bdsi-section bdsi-grid-bg"><div class="container-xl"><div class="row g-5 align-items-center"><div class="col-lg-6"><div class="bdsi-eyebrow">Tools & practice</div><h2 class="bdsi-title">Learn the tools in context</h2><p class="bdsi-copy mt-3">Instead of treating tools as isolated software, the course uses them as part of a workflow: understand the problem, work with data or code, validate the result and present or deploy the output.</p><div class="mt-4"><?php foreach($course['tools'] as $tool): ?><span class="bdsi-chip fs-6 p-3 me-2 mb-2"><?= htmlspecialchars($tool) ?></span><?php endforeach; ?></div></div><div class="col-lg-6"><div class="bdsi-card p-lg-5"><div class="bdsi-eyebrow">Learning format</div><h3 class="h2">Concept → Practice → Project → Review</h3><ul class="bdsi-list mt-4"><li>Instructor explanation and demonstration</li><li>Guided hands-on practice</li><li>Assignments and troubleshooting</li><li>Mini project or applied case</li><li>Review, improvement and interview discussion</li></ul></div></div></div></div></section>

<section class="bdsi-section"><div class="container-xl"><div class="row g-5"><div class="col-lg-6"><div class="bdsi-eyebrow">Career direction</div><h2 class="bdsi-title">Roles this course can support</h2><p class="bdsi-copy">Job readiness depends on your background, portfolio and practice. The course is designed to build relevant foundations for roles such as:</p><div class="row g-3 mt-3"><?php foreach($course['careers'] as $role): ?><div class="col-md-6"><div class="bdsi-card"><h4 class="h5 mb-0"><?= htmlspecialchars($role) ?></h4></div></div><?php endforeach; ?></div></div><div class="col-lg-6"><div class="bdsi-card p-lg-5"><div class="bdsi-eyebrow">Next step</div><h3 class="h2">Check whether this course fits your current level</h3><p class="bdsi-copy">A short counselling conversation can help identify prerequisites, suitable batch mode and whether you should start with a foundation module first.</p><button class="bdsi-btn mt-2" data-bs-toggle="modal" data-bs-target="#enquiryModal">Book Free Counselling</button></div></div></div></div></section>

<section class="bdsi-section bdsi-faq bdsi-grid-bg"><div class="container-xl"><div class="row g-5"><div class="col-lg-5"><div class="bdsi-eyebrow">Course FAQ</div><h2 class="bdsi-title"><?= htmlspecialchars($course['short']) ?> questions</h2></div><div class="col-lg-7"><div class="accordion" id="courseFaq"><div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button" data-bs-toggle="collapse" data-bs-target="#cfaq1">Who can join this course?</button></h3><div id="cfaq1" class="accordion-collapse collapse show" data-bs-parent="#courseFaq"><div class="accordion-body">Students, graduates, working professionals and career switchers can enquire. The recommended starting level depends on your current skills.</div></div></div><div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#cfaq2">Will I work on projects?</button></h3><div id="cfaq2" class="accordion-collapse collapse" data-bs-parent="#courseFaq"><div class="accordion-body">The learning plan includes practical exercises and applied project work appropriate to the selected course.</div></div></div><div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#cfaq3">Is placement guaranteed?</button></h3><div id="cfaq3" class="accordion-collapse collapse" data-bs-parent="#courseFaq"><div class="accordion-body">No job outcome should be treated as guaranteed. Career assistance focuses on skill building, projects, resume guidance and interview preparation.</div></div></div></div></div></div></div></section>
</main>
<?php require __DIR__ . '/includes/footer.php'; ?>
