<?php
require_once __DIR__ . '/includes/site-data.php';
$page = preg_replace('/[^a-z-]/', '', strtolower($_GET['page'] ?? ''));
$allowed = ['courses','about','blog','contact','industrial-training','college-training','tutorials','placements'];
if (!in_array($page, $allowed, true)) { http_response_code(404); $page='404'; }

$meta = [
 'courses'=>['All IT & Data Courses in Jaipur | Best Data Science Institute','Explore Data Science, Data Analytics, AI, Python, Power BI, Machine Learning, Web Development, Cloud and career-focused courses in Jaipur.'],
 'about'=>['About Best Data Science Institute Jaipur','Learn about Best Data Science Institute and its practical approach to data, AI, analytics and technology training in Jaipur.'],
 'blog'=>['Data Science, AI & Career Blog | BDSI Jaipur','Read practical learning guides about Data Science, Data Analytics, AI, Python, Power BI, careers and technology skills.'],
 'contact'=>['Contact Best Data Science Institute Jaipur','Contact Best Data Science Institute in Jaipur for course counselling, free demo scheduling and training enquiries.'],
 'industrial-training'=>['Industrial Training & Internship in Jaipur | BDSI','Explore practical industrial training and internship-oriented learning paths for students in Jaipur.'],
 'college-training'=>['College Training Programs in Jaipur | BDSI','Technology training options for colleges and student groups covering programming, data, AI, analytics and development skills.'],
 'tutorials'=>['Free Tutorials: Python, Data, AI & Coding | BDSI','Start with beginner-friendly tutorial topics in Python, SQL, data analytics, AI, machine learning and web development.'],
 'placements'=>['Career & Placement Assistance | BDSI Jaipur','Explore job-readiness, resume, project and interview preparation support at Best Data Science Institute Jaipur.'],
 '404'=>['Page Not Found | Best Data Science Institute','The requested page could not be found.'],
];
$pageTitle=$meta[$page][0];$pageDescription=$meta[$page][1];
$canonical=$bdsi['url'].'/'.($page==='404'?'404':$page.'.php');
require __DIR__.'/includes/header.php';

function hero(string $eyebrow,string $title,string $copy): void { echo '<section class="bdsi-page-hero"><div class="container-xl"><div class="bdsi-eyebrow">'.htmlspecialchars($eyebrow).'</div><h1>'.htmlspecialchars($title).'</h1><p class="bdsi-lead mt-3">'.htmlspecialchars($copy).'</p></div></section>'; }
?>
<main>
<?php if($page==='courses'): hero('Explore programs','Courses for data, AI, coding & digital careers','Choose a practical learning path based on your starting level and the role you want to work toward.'); ?>
<section class="bdsi-section"><div class="container-xl"><div class="row g-4"><?php foreach($courseCatalog as $c): ?><div class="col-md-6 col-xl-4"><article class="bdsi-card"><div class="bdsi-chip"><?=htmlspecialchars($c['category'])?></div><h2 class="h4 mt-2"><?=htmlspecialchars($c['short'])?></h2><p><?=htmlspecialchars($c['summary'])?></p><div class="mb-3"><?php foreach(array_slice($c['tools'],0,4) as $tool):?><span class="bdsi-chip"><?=htmlspecialchars($tool)?></span><?php endforeach;?></div><a href="<?=htmlspecialchars($c['route'])?>">View Course →</a></article></div><?php endforeach; ?></div>
<div class="mt-5"><div class="bdsi-eyebrow">More technology courses</div><div class="row g-3"><?php foreach($additionalRoutes as [$group,$label,$route]):?><div class="col-md-6 col-xl-3"><a class="bdsi-card d-block text-decoration-none text-white" href="<?=htmlspecialchars($route)?>"><span class="bdsi-chip"><?=htmlspecialchars($group)?></span><h3 class="h6 mt-2 mb-0"><?=htmlspecialchars($label)?></h3></a></div><?php endforeach;?></div></div></div></section>

<?php elseif($page==='about'): hero('About BDSI','Practical learning for modern technology careers','Best Data Science Institute focuses on structured, hands-on training that connects concepts with exercises, projects and career preparation.'); ?>
<section class="bdsi-section"><div class="container-xl"><div class="row g-5 align-items-center"><div class="col-lg-7"><div class="bdsi-eyebrow">Our approach</div><h2 class="bdsi-title">Skills are built through practice</h2><p class="bdsi-copy mt-3">Learners often struggle when advanced tools are taught before fundamentals. Our course paths are organized to build foundations first, then move into practical tools, projects and interview discussion.</p><p class="bdsi-copy">Programs cover data science, artificial intelligence, data analytics, programming, web development, cloud and related technology skills. Course counselling helps learners pick a suitable starting point.</p></div><div class="col-lg-5"><div class="bdsi-card p-lg-5"><h3>What guides the training</h3><ul class="bdsi-list mt-3"><li>Clear prerequisites</li><li>Instructor-led practical sessions</li><li>Assignments and project work</li><li>Role-focused learning paths</li><li>Career and interview preparation</li></ul><button class="bdsi-btn mt-3" data-bs-toggle="modal" data-bs-target="#enquiryModal">Book a Free Demo</button></div></div></div></div></section>
<section class="bdsi-section bdsi-grid-bg"><div class="container-xl"><div class="row g-4"><div class="col-md-4"><div class="bdsi-card"><h3 class="h4">Learn</h3><p>Understand concepts with examples and instructor guidance.</p></div></div><div class="col-md-4"><div class="bdsi-card"><h3 class="h4">Build</h3><p>Practice through exercises, dashboards, code and applied projects.</p></div></div><div class="col-md-4"><div class="bdsi-card"><h3 class="h4">Prepare</h3><p>Explain your work, revise interview concepts and map skills to roles.</p></div></div></div></div></section>

<?php elseif($page==='blog'): hero('Learning resources','Data, AI & career learning guides','A growing resource hub for students exploring technology careers, course roadmaps and practical skill development.'); ?>
<section class="bdsi-section"><div class="container-xl"><div class="row g-4"><div class="col-md-6 col-xl-4"><article class="bdsi-card"><div class="bdsi-chip">Data Analytics</div><h2 class="h4">How to start a Data Analytics career in Jaipur</h2><p>Understand the role of Excel, SQL, Power BI, Python, statistics and projects in a practical analyst roadmap.</p><a href="/data-analytics-course-jaipur/">Read the learning roadmap →</a></article></div><div class="col-md-6 col-xl-4"><article class="bdsi-card"><div class="bdsi-chip">Data Science</div><h2 class="h4">What should you learn before Machine Learning?</h2><p>A sensible sequence through Python, statistics, data cleaning and exploratory analysis before model building.</p><a href="/data-science-course-jaipur/">Explore the Data Science roadmap →</a></article></div><div class="col-md-6 col-xl-4"><article class="bdsi-card"><div class="bdsi-chip">Generative AI</div><h2 class="h4">LLMs, RAG and AI agents: where to begin</h2><p>Learn how Python, APIs, prompting, embeddings, retrieval and evaluation fit together.</p><a href="/generative-ai-course-jaipur/">Explore Generative AI →</a></article></div></div><div class="bdsi-card mt-5"><p class="mb-0">Existing indexed blog URLs from the previous website are being preserved through permanent redirects to the most relevant current content while the new blog library is expanded.</p></div></div></section>

<?php elseif($page==='contact'): hero('Contact','Talk to our course counselling team','Ask about course prerequisites, learning paths, batch mode or scheduling a free demo.'); ?>
<section class="bdsi-section"><div class="container-xl"><div class="row g-5"><div class="col-lg-5"><div class="bdsi-card p-lg-5"><div class="bdsi-eyebrow">Admissions</div><h2 class="h3">Best Data Science Institute</h2><p class="bdsi-copy">Jaipur, Rajasthan, India</p><a class="bdsi-btn w-100 mb-3" href="tel:+919116036041">Call +91 91160 36041</a><a class="bdsi-btn bdsi-btn-outline w-100" href="mailto:info@bestdatascienceinstitute.com">Email Admissions</a></div></div><div class="col-lg-7"><div class="bdsi-form-card"><h2 class="h3">Send an enquiry</h2><form class="bdsi-lead-form" action="/submit-enquiry.php" method="post"><div class="row g-3"><div class="col-md-6"><label>Full name *</label><input class="form-control" name="full_name" required></div><div class="col-md-6"><label>Mobile *</label><input class="form-control" name="phone" required></div><div class="col-md-6"><label>Email</label><input class="form-control" type="email" name="email"></div><div class="col-md-6"><label>City</label><input class="form-control" name="city" value="Jaipur"></div><div class="col-md-6"><label>Course *</label><input class="form-control" name="course" required placeholder="Course or query"></div><div class="col-md-6"><label>Qualification</label><input class="form-control" name="qualification"></div><input type="hidden" name="preferred_mode"><input type="hidden" name="source_url"><input type="hidden" name="utm_source"><input type="hidden" name="utm_medium"><input type="hidden" name="utm_campaign"><input type="hidden" name="utm_term"><input type="hidden" name="utm_content"><input type="text" name="website" style="position:absolute;left:-9999px" tabindex="-1"><div class="col-12"><button class="bdsi-btn w-100" type="submit">Submit Enquiry</button><div class="bdsi-toast"></div></div></div></form></div></div></div></div></section>

<?php elseif($page==='industrial-training'): hero('Industrial training','Project-focused training for students','Build practical exposure through structured technology training, guided assignments and project work relevant to your academic or career track.'); ?>
<section class="bdsi-section"><div class="container-xl"><div class="row g-4"><div class="col-md-6 col-xl-3"><div class="bdsi-card"><h3 class="h5">Data & Analytics</h3><p>Python, SQL, Excel, Power BI, statistics and project work.</p></div></div><div class="col-md-6 col-xl-3"><div class="bdsi-card"><h3 class="h5">AI & Machine Learning</h3><p>ML foundations, applied AI, GenAI and project-oriented learning.</p></div></div><div class="col-md-6 col-xl-3"><div class="bdsi-card"><h3 class="h5">Software Development</h3><p>Programming, web development, databases, Git and deployment basics.</p></div></div><div class="col-md-6 col-xl-3"><div class="bdsi-card"><h3 class="h5">Career Preparation</h3><p>Project explanation, resume alignment and interview concept revision.</p></div></div></div><div class="text-center mt-5"><button class="bdsi-btn" data-bs-toggle="modal" data-bs-target="#enquiryModal">Ask About Industrial Training</button></div></div></section>

<?php elseif($page==='college-training'): hero('For colleges','Technology training for student groups','Plan skill-development sessions, workshops and practical training tracks for college students across coding, data, AI and analytics.'); ?>
<section class="bdsi-section"><div class="container-xl"><div class="row g-5"><div class="col-lg-7"><h2 class="bdsi-title">Training formats that can match an academic schedule</h2><p class="bdsi-copy mt-3">Programs can be discussed around student level, target technology, available hours and desired project outcomes. The exact scope should be finalized with the college before delivery.</p><div class="row g-3 mt-3"><div class="col-md-6"><div class="bdsi-card"><h3 class="h5">Workshops</h3><p>Focused introductory sessions around a defined tool or technology.</p></div></div><div class="col-md-6"><div class="bdsi-card"><h3 class="h5">Skill Tracks</h3><p>Multi-session practical learning with assignments and guided work.</p></div></div><div class="col-md-6"><div class="bdsi-card"><h3 class="h5">Project Training</h3><p>Structured support around academic or portfolio projects.</p></div></div><div class="col-md-6"><div class="bdsi-card"><h3 class="h5">Career Sessions</h3><p>Technology roadmaps, project presentation and interview readiness.</p></div></div></div></div><div class="col-lg-5"><div class="bdsi-card p-lg-5"><h3>Discuss a college requirement</h3><p class="bdsi-copy">Contact the team with branch, student count, preferred technology and available training duration.</p><a class="bdsi-btn" href="/contact.php">Contact Us</a></div></div></div></div></section>

<?php elseif($page==='tutorials'): hero('Free learning','Tutorial topics to strengthen fundamentals','Use these topics as a starting checklist before moving into larger projects and role-focused programs.'); ?>
<section class="bdsi-section"><div class="container-xl"><div class="row g-4"><?php $topics=['Python Fundamentals'=>['Variables & data types','Conditions & loops','Functions','OOP basics'],'SQL & Databases'=>['SELECT queries','Joins','GROUP BY','Subqueries'],'Data Analytics'=>['Excel basics','Data cleaning','Power BI','Dashboard thinking'],'Machine Learning'=>['Regression','Classification','Model evaluation','Feature basics'],'Generative AI'=>['Prompting','LLM APIs','Embeddings','RAG basics'],'Web Development'=>['HTML','CSS','JavaScript','Git basics']]; foreach($topics as $name=>$items):?><div class="col-md-6 col-xl-4"><div class="bdsi-card"><h2 class="h4"><?=htmlspecialchars($name)?></h2><ul class="bdsi-list"><?php foreach($items as $item):?><li><?=htmlspecialchars($item)?></li><?php endforeach;?></ul></div></div><?php endforeach;?></div></div></section>

<?php elseif($page==='placements'): hero('Career support','Prepare to present your skills with confidence','Career support focuses on job readiness: portfolio quality, resume clarity, interview concepts and communicating what you actually built.'); ?>
<section class="bdsi-section"><div class="container-xl"><div class="row g-4"><div class="col-md-6 col-xl-3"><div class="bdsi-card"><h3 class="h5">Resume Review</h3><p>Align projects and skills with the type of role you are targeting.</p></div></div><div class="col-md-6 col-xl-3"><div class="bdsi-card"><h3 class="h5">Project Explanation</h3><p>Practice explaining decisions, tools, errors and outcomes from your work.</p></div></div><div class="col-md-6 col-xl-3"><div class="bdsi-card"><h3 class="h5">Interview Practice</h3><p>Revise role-relevant concepts and common technical discussion areas.</p></div></div><div class="col-md-6 col-xl-3"><div class="bdsi-card"><h3 class="h5">Job Readiness</h3><p>Understand gaps and next learning steps before applying broadly.</p></div></div></div><div class="bdsi-card mt-5"><strong>Important:</strong> Placement assistance is support for preparation and opportunities; it is not a guarantee of employment or salary.</div></div></section>

<?php else: hero('404','Page not found','The page you requested is unavailable.'); ?><section class="bdsi-section"><div class="container-xl"><a class="bdsi-btn" href="/">Return Home</a></div></section>
<?php endif; ?>
</main>
<?php require __DIR__.'/includes/footer.php'; ?>
