<?php require_once __DIR__ . '/site-data.php'; ?>
<footer class="bdsi-footer"><div class="container-xl"><div class="row g-5">
<div class="col-lg-4"><img src="/image/bdsi-logo.svg" alt="Best Data Science Institute" class="bdsi-logo mb-4"><p class="bdsi-copy">Practical technology training in Jaipur for Data Science, Artificial Intelligence, Data Analytics, Python, Power BI, Web Development and career-focused digital skills.</p><a href="tel:+91<?= htmlspecialchars($bdsi['phone']) ?>" class="mt-3 text-white fs-5"><?= htmlspecialchars($bdsi['phone_display']) ?></a><a href="mailto:<?= htmlspecialchars($bdsi['email']) ?>"><?= htmlspecialchars($bdsi['email']) ?></a></div>
<div class="col-6 col-lg-2"><h6>Explore</h6><a href="/courses.php">All Courses</a><a href="/about.php">About Us</a><a href="/industrial-training.php">Internship</a><a href="/placements.php">Placements</a><a href="/blog.php">Blog</a><a href="/contact.php">Contact</a></div>
<div class="col-6 col-lg-3"><h6>Popular Courses</h6><a href="/data-science-course-jaipur/">Data Science with AI</a><a href="/data-analytics-course-jaipur/">Data Analytics</a><a href="/python-course-jaipur/">Python Programming</a><a href="/generative-ai-course-jaipur/">Generative AI</a><a href="/machine-learning-course-jaipur/">Machine Learning</a><a href="/power-bi-course-jaipur/">Power BI</a></div>
<div class="col-lg-3"><h6>Start Learning</h6><p class="bdsi-copy">Not sure which course fits your goal? Request a counselling call or free demo.</p><button class="bdsi-btn" data-bs-toggle="modal" data-bs-target="#enquiryModal">Request Counselling</button></div>
</div><div class="copyright d-flex flex-column flex-md-row justify-content-between gap-2"><span>© <?= date('Y') ?> Best Data Science Institute. All rights reserved.</span><span>Jaipur, Rajasthan, India</span></div></div></footer>
<button class="bdsi-btn bdsi-floating" data-bs-toggle="modal" data-bs-target="#enquiryModal">Free Demo</button>
<div class="modal fade bdsi-modal" id="enquiryModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered modal-lg"><div class="modal-content"><div class="modal-header border-0 px-4 pt-4"><div><div class="bdsi-eyebrow mb-1">Course counselling</div><h3 class="mb-0">Book a Free Demo</h3></div><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body p-4 pt-2">
<form class="bdsi-lead-form bdsi-form-card p-0 border-0 shadow-none" action="/submit-enquiry.php" method="post"><div class="row g-3">
<div class="col-md-6"><label>Full name *</label><input class="form-control" name="full_name" required autocomplete="name" placeholder="Your name"></div><div class="col-md-6"><label>Mobile number *</label><input class="form-control" name="phone" required inputmode="tel" autocomplete="tel" pattern="[0-9+() -]{8,18}" placeholder="Mobile number"></div><div class="col-md-6"><label>Email</label><input class="form-control" type="email" name="email" autocomplete="email" placeholder="Email address"></div><div class="col-md-6"><label>City</label><input class="form-control" name="city" autocomplete="address-level2" value="Jaipur" placeholder="City"></div>
<div class="col-md-6"><label>Interested program *</label><select class="form-select" name="course" required><option value="">Choose course</option><option>Data Science with AI</option><option>Data Analytics</option><option>Python Programming</option><option>Generative AI</option><option>Agentic AI</option><option>Machine Learning</option><option>Power BI</option><option>Web Development</option><option>Full Stack Development</option><option>Cloud / DevOps</option><option>Cyber Security</option><option>Other</option></select></div><div class="col-md-6"><label>Current qualification</label><input class="form-control" name="qualification" placeholder="e.g. B.Tech, BCA, Graduate"></div><div class="col-md-6"><label>Preferred mode</label><select class="form-select" name="preferred_mode"><option value="">Choose mode</option><option>Classroom</option><option>Online</option><option>Hybrid</option></select></div><div class="col-md-6 d-flex align-items-end"><button class="bdsi-btn w-100" type="submit">Request Free Counselling</button></div></div>
<input type="hidden" name="source_url" value=""><input type="hidden" name="utm_source" value=""><input type="hidden" name="utm_medium" value=""><input type="hidden" name="utm_campaign" value=""><input type="hidden" name="utm_term" value=""><input type="hidden" name="utm_content" value=""><div style="position:absolute;left:-10000px" aria-hidden="true"><label>Website<input tabindex="-1" autocomplete="off" name="website"></label></div><div class="bdsi-toast" aria-live="polite"></div><p class="bdsi-form-note mt-3 mb-0">By submitting, you agree to be contacted about course counselling and demo scheduling.</p></form>
</div></div></div></div>
<script src="/js/vendor/jquery.min.js"></script><script src="/js/vendor/bootstrap.bundle.min.js"></script><script>
(function(){const params=new URLSearchParams(location.search);document.querySelectorAll('.bdsi-lead-form').forEach(function(form){const source=form.querySelector('[name="source_url"]');if(source)source.value=location.href;['utm_source','utm_medium','utm_campaign','utm_term','utm_content'].forEach(function(k){const el=form.querySelector('[name="'+k+'"]');if(el)el.value=params.get(k)||sessionStorage.getItem('bdsi_'+k)||'';if(params.get(k))sessionStorage.setItem('bdsi_'+k,params.get(k));});form.addEventListener('submit',async function(e){e.preventDefault();const btn=form.querySelector('button[type="submit"]'),msg=form.querySelector('.bdsi-toast');const old=btn.innerHTML;btn.disabled=true;btn.innerHTML='Submitting…';msg.className='bdsi-toast';try{const r=await fetch(form.action,{method:'POST',body:new FormData(form),headers:{'X-Requested-With':'XMLHttpRequest'}});const data=await r.json();if(!r.ok||!data.ok)throw new Error(data.message||'Unable to submit.');msg.textContent=data.message||'Thank you. Our counsellor will contact you shortly.';msg.className='bdsi-toast ok';form.reset();if(source)source.value=location.href;}catch(err){msg.textContent=err.message||'Unable to submit right now. Please call us.';msg.className='bdsi-toast err';}finally{btn.disabled=false;btn.innerHTML=old;}});});})();
</script></body></html>
